export const EXPERIENCES = [
	{
		company: "Lineman Wongnai",
		role: "Frontend Engineer Intern",
		period: "May - July 2024",
		duration: "2 months",
		responsibilities: [
			"Worked in the AdTech team, focusing on advertisement services (data collection, ad display, ad purchasing, and ad manager UI for user)",
			"Followed Agile methodologies to boost productivity",
			"Developed, enhanced, and debugged UI in webviews using React/React Native and Styled Components",
			"Delivered a new UI for the upcoming advertisement credit system",
			"Built and maintained internal libraries for UI components and tracking user interactions (clicks, views, navigation)",
			"Test-driven development (TDD) by writing unit tests using Jest and Vitest",
			"Wrote automated E2E tests (Playwright, Cypress) in a CI/CD pipeline",
			"Adhered to strict coding standards, improving code quality",
			"Learned to communicate and cooperate with backend, QA, and UX teams",
		],
		skills: [
			"React",
			"React Native",
			"TDD",
			"Jest",
			"Vitest",
			"Playwright",
			"Cypress",
			"CI/CD",
		],
	},
	{
		company: "Lineman Wongnai",
		role: "Backend Engineer Intern",
		period: "May - July 2025",
		duration: "2 months",
		responsibilities: [
			"Worked in the Fleet team, creating features for delivery service riders and operation admins",
			"Followed Kanban methodologies to boost productivity",
			"Created APIs with Gin HTTP server and gRPC server using Golang",
			"Built admin UI for operational management",
			"Test-driven development (TDD) by writing unit tests and integration tests",
			"Used MongoDB and VOS (Verda Object Storage, service of Verda, infrastructure of LINE corp)",
			"Utilizing ArgoCD deployment pipeline",
			"Performance monitoring with Grafana",
			"Log querying with OpenSearch",
			"Features rollout with Unleash feature flag management",
		],
		skills: [
			"Go",
			"Gin",
			"gRPC",
			"MongoDB",
			"ArgoCD",
			"Grafana",
			"OpenSearch",
			"Unleash",
		],
	},
];
